// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbGdLHL2VfWSC_le_tpGpaKdoDTGM6hAA',
    appId: '1:460148246238:web:8e0b8ada0ed39ecca9e44f',
    messagingSenderId: '460148246238',
    projectId: 'taskslide-71164',
    authDomain: 'taskslide-71164.firebaseapp.com',
    storageBucket: 'taskslide-71164.appspot.com',
    measurementId: 'G-0YJX14YQ4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG88gg5O6JEZ_Q8xvgVvndVcPNt1yE9-w',
    appId: '1:460148246238:android:4a212cab6b4695d8a9e44f',
    messagingSenderId: '460148246238',
    projectId: 'taskslide-71164',
    storageBucket: 'taskslide-71164.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiWAGVnVz4bee1zVptfDvQzh_T3TD5aXE',
    appId: '1:460148246238:ios:4a05dc117d224800a9e44f',
    messagingSenderId: '460148246238',
    projectId: 'taskslide-71164',
    storageBucket: 'taskslide-71164.appspot.com',
    androidClientId: '460148246238-puujng4812deo8c1afk7pb5nrin81d3o.apps.googleusercontent.com',
    iosClientId: '460148246238-h04743jo67p9vs557rvcjlrt4i93tr3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskslide',
  );
}
